services:
  greengrass-lite:
    image: greengrass-lite-2layer:v5
    container_name: greengrass-lite
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./volumes/etc-greengrass:/etc/greengrass
      - ./volumes/var-lib-greengrass:/var/lib/greengrass
    tmpfs:
      - /run
      - /run/lock
