services:
  greengrass-lite:
    image: ghcr.io/thomas-roos/greengrass-lite:latest
    container_name: greengrass-lite
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - ./volumes/etc-greengrass:/etc/greengrass
      - ./volumes/var-lib-greengrass:/var/lib/greengrass
      - ./volumes/var-lib-containers:/var/lib/containers
      - ./volumes/greengrass-lite.target.wants:/etc/systemd/system/greengrass-lite.target.wants
      - ./volumes/etc-containers:/etc/containers:ro
      - ./volumes/subuid:/etc/subuid:ro
      - ./volumes/subgid:/etc/subgid:ro
    tmpfs:
      - /run
      - /run/lock
