services:
  greengrass-lite:
    image: ghcr.io/thomas-roos/greengrass-lite:latest
    container_name: greengrass-lite
    restart: unless-stopped
    privileged: true
    dns: []
    volumes:
      - ./volumes/etc-greengrass:/etc/greengrass
      - ./volumes/var-lib-greengrass:/var/lib/greengrass
      - ./volumes/resolv.conf:/etc/resolv.conf:ro
    tmpfs:
      - /run
      - /run/lock
      - /etc:exec
